[package]
name = "dest"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
rand = { version = "0.9.1", features = ["small_rng"] }
tokio = { version = "1.46.0", features = ["full", "rt", "rt-multi-thread"] }
